language: java
jdk:
  - openjdk7
scala:
   - 2.10.4
env:
- PLAY_VERSION=2.2.3

before_script:
- wget https://downloads.typesafe.com/play/2.2.3/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script:
-  sbt test
