language: java
jdk:
  - openjdk7
scala:
   - 2.10.4
env:
- PLAY_VERSION=2.2.6

before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script:
-  sbt test
